require "rmfluxus_rails/layout_rmfluxus.rb"

# Tabela de Movimentos

module RmfluxusRails
  module LayoutNF
    class Movimento
      include LayoutRmfluxus
     
      attr_numerico           :codfilial,              :tamanho => 5        # CÛdigo da Filial                              
      attr_alfa               :coddepartamento,        :tamanho => 30       # CÛdigo do Departamento                        
      attr_alfa               :codloc,                 :tamanho => 15       # CÛdigo do Local de Estoque                    
      attr_alfa               :codlocentrega,          :tamanho => 15       # CÛdigo do Local de Entrega                    
      attr_alfa               :codlocdestino,          :tamanho => 15       # CÛdigo do Local de Destino                    
      attr_alfa               :codcfo,                 :tamanho => 25       # CÛdigo do Cliente / Fornecedor                
      attr_alfa               :codcfonatureza,         :tamanho => 25       # CÛdigo Cliente / Fornecedor RM Fluxus         
      attr_alfa               :numeromov,              :tamanho => 35       # N˙mero do Movimento                           
      attr_alfa               :serie,                  :tamanho => 8        # SÈrie                                         
      attr_alfa               :codtmv,                 :tamanho => 10       # CÛdigo do Tipo de Movimento                   
      attr_alfa               :tipo,                   :tamanho => 1        # Tipo                                          
      attr_alfa               :status,                 :tamanho => 1        # Status                                        
      attr_numerico           :movimpresso,            :tamanho => 1        # Identificador de Movimento Impresso           
      attr_numerico           :docimpresso,            :tamanho => 1        # Documento Impresso                            
      attr_numerico           :fatimpressa,            :tamanho => 1        # Fatura Impressa                               
      attr_data               :dataemissao,            :tamanho => 10       # Data da Emiss„o                               
      attr_data               :datasaida,              :tamanho => 10       # Data da SaÌda                                 
      attr_data               :dataextra1,             :tamanho => 10       # Data Extra1                                   
      attr_data               :dataextra2,             :tamanho => 10       # Data Extra2                                   
      attr_alfa               :codrpr,                 :tamanho => 15       # CÛdigo do Representante                       
      attr_valor_financeiro   :comissaorepres,         :tamanho => 20       # Comiss„o do Representante                     
      attr_alfa               :nordem,                 :tamanho => 20       # N˙mero Ordem                                  
      attr_alfa               :codcpg,                 :tamanho => 5        # CÛdigo da CondiÁ„o de Pagamnto                
      attr_numerico           :numerotributos,         :tamanho => 5        # N˙mero dos Tributos                           
      attr_valor_financeiro   :valorbruto,             :tamanho => 20       # Valor Bruto                                   
      attr_valor_financeiro   :valorliquido,           :tamanho => 20       # Valor LÌquido                                 
      attr_valor_financeiro   :valoroutros,            :tamanho => 20       # Valor de Outros                               
      attr_alfa               :observacao,             :tamanho => 60       # ObservaÁ„o                                    
      attr_valor_financeiro   :percentualfrete,        :tamanho => 20       # Percentual do Frete                           
      attr_valor_financeiro   :valorfrete,             :tamanho => 20       # Valor do Frete                                
      attr_valor_financeiro   :percentualseguro,       :tamanho => 20       # Percentual do Segura                          
      attr_valor_financeiro   :valorseguro,            :tamanho => 20       # Valor do Seguro                               
      attr_valor_financeiro   :percentualdesc,         :tamanho => 20       # Percentual do Desconto                        
      attr_valor_financeiro   :valordesc,              :tamanho => 20       # Valor do Desconto                             
      attr_valor_financeiro   :percentualdesp,         :tamanho => 20       # Percentual da Despesa                         
      attr_valor_financeiro   :valordesp,              :tamanho => 20       # Valor da Despesa                              
      attr_valor_financeiro   :percentualextra1,       :tamanho => 20       # Percentual Extra1                             
      attr_valor_financeiro   :valorextra1,            :tamanho => 20       # Valor Extra1                                  
      attr_valor_financeiro   :percentualextra2,       :tamanho => 20       # Percentual Extra2                             
      attr_valor_financeiro   :valorextra2,            :tamanho => 20       # Valor Extra2                                  
      attr_alfa               :codven1,                :tamanho => 16       # CÛdigo do Vendedor 1                          
      attr_valor_financeiro   :perccomissao,           :tamanho => 20       # Percentual Comiss„o                           
      attr_alfa               :codmen,                 :tamanho => 5        # CÛdigo da Mensagem                            
      attr_alfa               :codmen2,                :tamanho => 5        # CÛdigo da Mensagem2                           
      attr_alfa               :viadetransporte,        :tamanho => 15       # Via de Transporte                             
      attr_alfa               :placa,                  :tamanho => 10       # Placa                                         
      attr_alfa               :codetdplaca,            :tamanho => 2        # CÛdigo do Estado na Placa                     
      attr_valor_financeiro   :pesoliquido,            :tamanho => 20       # Peso LÌquido                                  
      attr_valor_financeiro   :pesobruto,              :tamanho => 20       # Peso Bruto                                    
      attr_alfa               :marca,                  :tamanho => 10       # Marca                                         
      attr_numerico           :numero,                 :tamanho => 10       # NumeraÁ„o da Mercadoria Transportada          
      attr_numerico           :quantidade,             :tamanho => 10       # Quantidade                                    
      attr_alfa               :especie,                :tamanho => 15       # EspÈcie                                       
      attr_alfa               :codtb1fat,              :tamanho => 10       # CÛdigo Tabela ClassificaÁ„o1 Produto          
      attr_alfa               :codtb2fat,              :tamanho => 10       # CÛdigo Tabela ClassificaÁ„o2 Produto          
      attr_alfa               :codtb3fat,              :tamanho => 10       # CÛdigo Tabela ClassificaÁ„o3 Produto          
      attr_alfa               :codtb4fat,              :tamanho => 10       # CÛdigo Tabela ClassificaÁ„o4 Produto          
      attr_alfa               :codtb5fat,              :tamanho => 10       # CÛdigo Tabela ClassificaÁ„o5 Produto          
      attr_alfa               :codtb1flx,              :tamanho => 25       # CÛdigo Tabela ClassificaÁ„o1 Opcionais        
      attr_alfa               :codtb2flx,              :tamanho => 25       # CÛdigo Tabela ClassificaÁ„o2 Opcionais        
      attr_alfa               :codtb3flx,              :tamanho => 25       # CÛdigo Tabela ClassificaÁ„o3 Opcionais        
      attr_alfa               :codtb4flx,              :tamanho => 25       # CÛdigo Tabela ClassificaÁ„o4 Opcionais        
      attr_alfa               :codtb5flx,              :tamanho => 25       # CÛdigo Tabela ClassificaÁ„o5 Opcionais        
      attr_alfa               :campolivre1,            :tamanho => 100      # Campo Livre1                                  
      attr_alfa               :campolivre2,            :tamanho => 100      # Campo Livre2                                  
      attr_alfa               :campolivre3,            :tamanho => 100      # Campo Livre3                                  
      attr_alfa               :codmoevalorliquido,     :tamanho => 10       # CÛdigo da Moeda no Valor LÌquido              
      attr_data               :databasemov,            :tamanho => 10       # Data Base do Movimento                        
      attr_data               :datamovimento,          :tamanho => 10       # Data do Movimento                             
      attr_numerico           :numerolctgerado,        :tamanho => 5        # N˙mero de LanÁamento Gerado                   
      attr_numerico           :geroufatura,            :tamanho => 5        # Gerou Fatura                                  
      attr_numerico           :numerolctaberto,        :tamanho => 5        # N˙imero de LanÁamento Aberto                  
      attr_alfa               :codven2,                :tamanho => 16       # CÛdigo do Vendedor 2                          
      attr_alfa               :codusuario,             :tamanho => 20       # CÛdigo do Usu·rio                             
      attr_numerico           :flagexportacao,         :tamanho => 5        # Flag ExportaÁ„o                               
      attr_alfa               :emiteboleta,            :tamanho => 1        # Emite Boleta                                  
      attr_alfa               :codmendesconto,         :tamanho => 5        # CÛdigo da Mensagem de Desconto                
      attr_alfa               :codmendespesa,          :tamanho => 5        # CÛdigo das Mensagem de Despesa                
      attr_alfa               :codmenfrete,            :tamanho => 5        # CÛdigo da Mensagem de Frete                   
      attr_numerico           :fretecifoufob,          :tamanho => 5        # Frete Cif ou Fob                              
      attr_numerico           :usadespfinanc,          :tamanho => 5        # Usa Despesa Financeira                        
      attr_numerico           :idnat,                  :tamanho => 5        # Identificador da Natureza                     
      attr_numerico           :flagexporfisc,          :tamanho => 5        # Flag ExportaÁ„o Fisc                          
      attr_numerico           :flagexporfazenda,       :tamanho => 5        # Flag ExportaÁ„o da Fazenda                    
      attr_alfa               :codven3,                :tamanho => 16       # CÛdigo do Vendedor 3                          
      attr_alfa               :codven4,                :tamanho => 16       # CÛdigo do Vendedor 4                          
      attr_valor_financeiro   :perccomissaoven2,       :tamanho => 20       # Percentual Comiss„o do Vendedor 2             
      attr_numerico           :idnat2,                 :tamanho => 5        # Identificador da Natureza 2                   
      attr_valor_financeiro   :valoradiantamento,      :tamanho => 20       # Valor Adiantamento                            
      attr_alfa               :codtra,                 :tamanho => 5        # CÛdigo da Transportadora                      
      attr_alfa               :codtra2,                :tamanho => 5        # CÛdigo da Transportadora2                     
      attr_numerico           :statusliberacao,        :tamanho => 5        # Status de LiberaÁ„o                           
      attr_numerico           :itensagrupados,         :tamanho => 5        # Itens Agrupados                               
      attr_alfa               :flagimpressaofat,       :tamanho => 1        # Flag Impress„o do Faturamento                 
      attr_data               :datacancelamentomov,    :tamanho => 10       # Data Cancelamento do Movimento                
      attr_alfa               :segundonumero,          :tamanho => 20       # Segundo N˙mero                                
      attr_alfa               :codccusto,              :tamanho => 25       # Centro de Custo                               
      attr_numerico           :codcolcxa,              :tamanho => 5        # Coligada da Conta/Caixa                       
      attr_alfa               :codcxa,                 :tamanho => 10       # Conta/Caixa                                   
      attr_numerico           :codfilialdestino,       :tamanho => 5        # CÛdigo da Filial de Destino                   
      attr_alfa               :codccustodestino,       :tamanho => 25       # Centro de Custo Destino (Transf.)             
      attr_numerico           :codcolcfo,              :tamanho => 5        # Coligada do Cliente/Fornecedor                
      attr_numerico           :codcolcfonatureza,      :tamanho => 5        # Coligada do Cli./Fornecedor Cpr               
      attr_numerico           :idmovlctfluxus,         :tamanho => 10       # Identificador Mov  LanÁamentos Pag/Rec        
      attr_data               :dataentrega,            :tamanho => 10       # Data de Entrega                               
      attr_numerico           :numerocaixa,            :tamanho => 10       # N˙mero do Caixa                               
      attr_numerico           :numerocupom,            :tamanho => 10       # N˙mero do Cupom                               
      attr_data               :horarioemissao,         :tamanho => 20       # Hor·rio da Emiss„o do Movimento               
      attr_numerico           :codfilialentrega,       :tamanho => 5        # CÛdigo da Filial de Entrega/SaÌda             
      attr_alfa               :codnat,                 :tamanho => 20       #                                               
      attr_alfa               :codnat2,                :tamanho => 20       #                                               
      attr_alfa               :cgccfo,                 :tamanho => 20       #                                               
      attr_data               :datacontabilizacao,     :tamanho => 10       # Data de contabilizaÁ„o do movimento           
      attr_alfa               :codigoservico,          :tamanho => 15       # CÛdigo do ServiÁo                             
      attr_alfa               :codmunservico,          :tamanho => 20       # MunicÌpio da prestaÁ„o de serviÁo             
      attr_alfa               :codetdmunserv,          :tamanho => 2        # CÛdigo do Estado do MunicÌpio                 
      attr_alfa               :pontovenda,             :tamanho => 10       # CÛdigo do Ponto de Venda                      
      attr_numerico           :codevento,              :tamanho => 10       # Evento ContabÌl                               
      attr_alfa               :codtdo,                 :tamanho => 10       # CÛdigo do tipo de documento                   
      attr_alfa               :codigoirrf,             :tamanho => 10       # CÛdigo de retenÁ„o do IRRF                    
      attr_valor_financeiro   :deducaoirrf,            :tamanho => 20       # Percentual de deduÁ„o para IRRF               
      attr_valor_financeiro   :percbaseinssempregado,  :tamanho => 20       # Perc.da Base de INSS Empregado                
      attr_valor_financeiro   :percentbaseinss,        :tamanho => 20       # Perc.da Base de INSS Empregador               
      attr_alfa               :codprj,                 :tamanho => 24       #                                               
      attr_numerico           :revisao,                :tamanho => 5        #                                               
      attr_alfa               :subserie,               :tamanho => 8        # Sub SÈrie                                     
      attr_numerico           :idcontatoentrega,       :tamanho => 10       # Contato p/ Entrega                            
      attr_valor_financeiro   :inssemoutraempresa,     :tamanho => 20       # Valor do INSS em Outra Empresa                
      attr_numerico           :apropriado,             :tamanho => 5        # Deve-se Apropriar Mov.Integ.ao RM Solum       
      attr_data               :datalancamento,         :tamanho => 10       # Data de lanÁamento                            
      attr_numerico           :cro,                    :tamanho => 10       # Contador de ReinÌcio de OperaÁ„o              
      attr_numerico           :coo,                    :tamanho => 10       #                                               
      attr_numerico           :numeroreducao,          :tamanho => 10       #                                               
      attr_data               :horasaida,              :tamanho => 20       # Hor·rio de entrada/saÌda do movimento         
      attr_alfa               :codentrega,             :tamanho => 15       # Tipo de Entrega                               
      attr_alfa               :recibonfestatus,        :tamanho => 1        # Status do Recibo                              
      attr_numerico           :recibonfetipo,          :tamanho => 5        # Tipo do Recibo                                
      attr_numerico           :recibonfesituacao,      :tamanho => 5        # SituaÁ„o do Recibo                            
      attr_alfa               :nroaidf,                :tamanho => 30       #                                               
      attr_alfa               :chaveacessonfe,         :tamanho => 44       # Chave de Acesso da NF-e                       
      attr_numerico           :extenporaneo,           :tamanho => 5        # … movimento extempor‚neo?                     
      
      # attr_alfa :, :tamanho => 
      # attr_valor_financeiro :, :tamanho =>
      # attr_numerico :, :tamanho => 
      # attr_data :, :tamanho => 
      # attr_nao_utilizado :, :tamanho => 
    end
  end
end